=== danielbrown96/super-shuffle/data/heroes-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "name": {
                "type": "string"
            },
            "team": {
                "type": "string",
                "enum": [
                    "X-Men",
                    "Avengers",
                    "Shield",
                    ""
                ]
            },
            "set": {
                "type": "string",
                "enum": [
                    "Core"
                ]
            },
            "classes": {
                "type": "object",
                "properties": {
                    "strength": {
                        "type": "integer",
                        "minimum": 1,
                        "maximum": 14
                    },
                    "range": {
                        "type": "integer",
                        "minimum": 1,
                        "maximum": 14
                    },
                    "instinct": {
                        "type": "integer",
                        "minimum": 1,
                        "maximum": 14
                    },
                    "covert": {
                        "type": "integer",
                        "minimum": 1,
                        "maximum": 14
                    },
                    "tech": {
                        "type": "integer",
                        "minimum": 1,
                        "maximum": 14
                    }
                }
            },
            "mechanical-tags": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "discard": {
                            "type": "integer"
                        },
                        "card-draw": {
                            "type": "integer"
                        },
                        "bystanders": {
                            "type": "integer"
                        },
                        "protection": {
                            "type": "integer"
                        },
                        "deck-manipulation": {
                            "type": "integer"
                        }
                    }
                }
            },
            "synergy-tags": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "discard": {
                            "type": "integer"
                        },
                        "team-xmen": {
                            "type": "integer"
                        },
                        "team-avengers": {
                            "type": "integer"
                        },
                        "class-strength": {
                            "type": "integer"
                        },
                        "class-tech": {
                            "type": "integer"
                        },
                        "colors": {
                            "type": "integer"
                        },
                        "bystanders": {
                            "type": "integer"
                        },
                        "class-ranged": {
                            "type": "integer"
                        },
                        "class-covert": {
                            "type": "integer"
                        },
                        "class-instinct": {
                            "type": "integer"
                        },
                        "deck-manipulation": {
                            "type": "integer"
                        }
                    }
                }
            },
            "thematic-tags": {
                "type": "array",
                "items": {
                    "type": "string",
                    "enum": [
                        "xmen",
                        "og-xmen",
                        "mutant",
                        "summers-family",
                        "x-force",
                        "deadpool",
                        "deadpool-and-wolverine",
                        "military",
                        "shield",
                        "mercenary",
                        "russians",
                        "avengers",
                        "spies",
                        "hellions",
                        "villain-and-hero",
                        "thief",
                        "hellfire-club"
                    ]
                }
            },
            "ability-tags": {
                "type": "array",
                "items": {
                    "type": "string",
                    "enum": [
                        "blaster",
                        "lasers",
                        "energy-controller",
                        "telepath",
                        "telekinesis",
                        "super-strength",
                        "guns",
                        "martial"
                    ]
                }
            },
            "purchasing-power": {
                "type": "integer",
                "minimum": 0,
                "maximum": 14
            },
            "attacking-power": {
                "type": "integer",
                "minimum": 0,
                "maximum": 14
            }
        },
        "required": [
            "name",
            "classes",
            "mechanical-tags",
            "synergy-tags",
            "thematic-tags",
            "ability-tags",
            "purchasing-power",
            "attacking-power"
        ]
    }
}

=== danielbrown96/super-shuffle/data/heroes.json
[
    {
        "name": "Black Widow",
        "team": "Avengers",
        "set": "Core",
        "classes": {"covert": 9, "tech": 5},
        "mechanical-tags": [{"bystanders": 11}, {"card-draw": 5}],
        "synergy-tags": [{"class-tech": 5},{"class-covert": 5},{"bystanders": 3}],
        "thematic-tags": ["avengers", "spies", "russians", "shield"],
        "ability-tags": ["martial", "guns"],
        "purchasing-power": 0,
        "attacking-power": 9
    },
    {
        "name": "Captain America",
        "team": "Avengers",
        "set": "Core",
        "classes": {"instinct": 5, "strength": 5, "tech": 3, "covert": 1},
        "mechanical-tags": [{"protection": 5}],
        "synergy-tags": [{"team-avengers": 1}, {"colors": 10}, {"class-instinct": 5}, {"class-strength": 5}, {"class-covert": 10}, {"class-ranged": 10}, {"class-tech": 10}],
        "thematic-tags": ["avengers", "military", "shield"],
        "ability-tags": ["super-strength"],
        "purchasing-power": 5,
        "attacking-power": 9
    }
]

=== danielbrown96/super-shuffle/data/heroes/deadpool.json
{
    "name": "Deadpool",
    "team": "",
    "set": "Core",
    "classes": {"tech": 5, "covert": 5, "instinct": 4},
    "mechanical-tags": [{"bystander": 5}, {"discard": 3}, {"card-draw": 3}],
    "synergy-tags": [],
    "thematic-tags": ["deadpool", "deadpool-and-wolverine", "mutant", "mercenary", "x-force"],
    "ability-tags": ["guns"],
    "purchasing-power": 0,
    "attacking-power": 0
}

=== danielbrown96/super-shuffle/data/heroes/captain-america.json
{
    "name": "Captain America",
    "team": "Avengers",
    "set": "Core",
    "classes": {"instinct": 5, "strength": 5, "tech": 3, "covert": 1},
    "mechanical-tags": [{"protection": 5}],
    "synergy-tags": [{"team-avengers": 1}, {"colors": 10}, {"class-instinct": 5}, {"class-strength": 5}, {"class-covert": 10}, {"class-ranged": 10}, {"class-tech": 10}],
    "thematic-tags": ["avengers", "military", "shield"],
    "ability-tags": ["super-strength"],
    "purchasing-power": 5,
    "attacking-power": 9
}

=== danielbrown96/super-shuffle/data/heroes/black-widow.json
{
    "name": "Black Widow",
    "team": "Avengers",
    "set": "Core",
    "classes": {"covert": 9, "tech": 5},
    "mechanical-tags": [{"bystanders": 11}, {"card-draw": 5}],
    "synergy-tags": [{"class-tech": 5},{"class-covert": 5},{"bystanders": 3}],
    "thematic-tags": ["avengers", "spies", "russians", "shield"],
    "ability-tags": ["martial", "guns"],
    "purchasing-power": 0,
    "attacking-power": 9
}
